### ISSUE TITLE
Ignore WM_NORMAL_HINTS resize increment for tiled windows

### ISSUE THREAD

**Issue by dtolnay** [paperwm/PaperWM#106]
If I run the following in gnome-terminal:

```bash
xprop -id $(xdotool getwindowfocus)
```

part of the output shows:

```console
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 506 by 214
		program specified resize increment: 18 by 36
		program specified base size: 104 by 162
		window gravity: NorthWest
```

The middle line means that gnome-terminal requests for the window height to always be an integer multiple of the row height which is 36 pixels. Usually tiling window managers ignore this hint and always size the window as required by the tile. Would it be possible for PaperWM to behave this way too, or does gnome-shell make it impossible to ignore the hint?

I believe the undesirable behavior is visible in the tiling.png screenshot in the readme, where you can see the terminal window is a few pixels different in height from all the other windows.

Scratch windows should continue to respect the resize increment.

**Comment by olejorgenb** [comment]
We've looked into this in the past and found that gnome-shell/mutter does not expose such functionality. AFAIK the hints themself are not exposed either [1] (nor the xwindow id).

Things like this is the price to pay for piggybacking on gnome-shell. We get alot in return though :)

Even when ignoring the hints as some tiling managers does, it's still up to the application to decide whether to actually honor the request. Urxvt rounded non-standard size requests made by [notion](http://notion.sourceforge.net/)

Some applications can be configured to not set the hints (`frame-resize-pixelwise` in emacs). Tilix is an terminal emulator that does not set the hints at all.

[1] Leading to rather interesting layout code since we can't know in advance if a window will/is likely to honor a resize request.

PS: I'd love to proven wrong on this :)

**Comment by dtolnay** [comment]
Thanks for the explanation! I have a patched urxvt that behaves as a I want, so the limitation doesn't affect me.

```diff
--- rxvt-unicode-9.22.orig/src/main.C
+++ rxvt-unicode-9.22/src/main.C
@@ -737,8 +737,8 @@ rxvt_term::window_calc (unsigned int new
         window_vt_x += sb_w;
     }
 
-  szHint.width_inc  = fwidth;
-  szHint.height_inc = fheight;
+  szHint.width_inc  = 1;
+  szHint.height_inc = 1;
   szHint.min_width  = szHint.base_width + szHint.width_inc;
   szHint.min_height = szHint.base_height + szHint.height_inc;
```
