### ISSUE TITLE
multi-monitor: topbar jumping following the mouse

### ISSUE THREAD

**Issue by goodwillcoding** [paperwm/PaperWM#112]
OS: Ubuntu 18.04.2
Gnome: 3.28 (Gnome X11 session, not Unity)
PaperWM: master branch, e1f6a980ef16dbc1f28f442de5c1c9efca3fb424

When using multiple window the top bar follows the mouse, changing location to which ever monitor the mouse is on. I am not sure if this is a feature or a bug but over all visual effect is rather annoying as the topbar movement is very distracting.

**Comment by hedning** [comment]
It's intended, for a few reasons:
- To indicate which monitor has focus
- Active workspaces on non-primary monitors looked weird having the space for the top bar not filled

Mutter/gnome-shell only support having one active workspace at the time, meaning it's not possible to interact with windows that's part of an inactive workspace. To work around this we show clones of the windows on monitors that's not active and force workspace focus to follow the mouse which results in the top bar also following the mouse.

Now that we support not showing the top-bar, it might be better to fill out workspaces on non-primary monitors completely. This will require building a simple top bar that will be shown when using the workspace carousel though.

**Comment by goodwillcoding** [comment]
I guess a related question is whether it's possible to treat multiple monitors as 1 workspace which would by pass this problem. I know that's not how i3 or other tiling managers do it. Not sure what your take on that is my guess it would be a fairly large feature.

**Comment by hedning** [comment]
Yeah, we did consider going that direction when building the multiple monitor support, but came to the conclusion that adding/removing monitors becomes rather weird, and not just technically.

In a one workspace per monitor world, adding monitor simply gives a view of an extra workspace. Removing a monitor just takes a view away. The workspaces remain unchanged, and since windows are tiled it's perfectly workable to move workspaces across monitors (something that doesn't quite work as well with floating windows).

When a workspace instead spans all monitors you'll have to split and merge a workspace across the available monitors. This becomes pretty messy, and I'm not really convinced there's a solution that can stand up to the simplicity of just having a workspace span one monitor.

But yeah, as said, making secondary monitors just fill out the vertical space completely and keep the top bar on primary is probably the right solution to this.

**Comment by jtaala** [comment]
Closing as I note that this option (`Make topbar follow monitor focus`) is user-settable in PaperWM settings.
