### ISSUE TITLE
Disable workspaces

### ISSUE THREAD

**Issue by jvnknvlgl** [paperwm/PaperWM#117]
While I like the concept of having a horizontally scrollable desktop, I am not a fan of the changes it makes to my workspaces (different wallpapers, for example) and I would prefer to just use the default Gnome activities overview. Is there, or can there be some way to disable PaperWM's workspaces?

**Comment by hedning** [comment]
You can set a default wallpaper from the preference gui. There's also a preference to turn off the workspace name and enable the hot corner:
```bash
dconf write /org/gnome/shell/extensions/paperwm/default-background '/path/to/image.png'
dconf write /org/gnome/shell/extensions/paperwm/use-workspace-name false
dconf write /org/gnome/shell/extensions/paperwm/override-hot-corner false
```

There's a discussion around letting workspaces span available monitors here #112, and the reasoning behind having a workspace per monitor (adding a preference for this would take a lot of work too).

We don't modify the activity overview much (apart from sorting the windows in their tiled order), you can still click on the top left corner label and the overview will pop up.

**Comment by jvnknvlgl** [comment]
There still is changed behaviour when using the Ctrl-Alt-Arrow key combination when switching between workspaces. Not much, but still something.

Anyhow, I'm going to be using this for a couple of weeks to see if it sticks but for now I'm very enthusiastic. Great work by all contributors!

**Comment by hedning** [comment]
Right, there's https://github.com/paperwm/PaperWM/pull/115 which aims to introduce sequential workspace navigation.

**Comment by NayamAmarshe** [comment]
Is this still in consideration? I'd like to disable workspaces altogether, or at least keep just 1 workspace if possible. I don't like the accidental switches to other workspaces.

**Comment by Lythenas** [comment]
@NayamAmarshe If you just want one workspace (and have only one monitor) you could try setting the "Number of Workspaces" to 1 in Gnome Settings, Multitasking. Haven't tried this, but it is worth a shot.

Regarding it this is still under consideration: I think so. But parts of this (especially the "use default gnome activity overview" part) are probably hard to implement. But if someone wants to implement this (e.g. as separate preference) I think we are open to it.

**Comment by Polisson** [comment]
Also, I'm looking for such an option, but let me describe the exact meaning (because now last two posts concludes to disable workspaces at all in the whole Gnome Shell).
Rolling-windows-to-sides feature of PaperWM is gorgeous! But user may need to use only that. 
IMHO, the best way is to provide an option to disable PaperWM's overview effect, so users could rely on the default Gnome overview, switching workspaces and other extensions ([V-Shell (Vertical Workspaces)](https://extensions.gnome.org/extension/5177/vertical-workspaces/), [Gesture Improvements](https://extensions.gnome.org/extension/4245/gesture-improvements/)). 
So one gestures type (4-finger) has to interact with Gnome default features and the other type (3-finger) then interacts with PaperWM canva.

**Comment by jtaala** [comment]
> PaperWM's overview effect

I'm confused by this - what do you mean PaperWM's overview effect?  You mean workspace stack switching?

Currently, three-finger swipe down initiates workspace stack switching, whereas three finger swipe up initiates Gnome overview.

**Comment by jtaala** [comment]
So, currently PaperWM manages gestures for 3 or more fingers (although it really only uses the 3 finger gestures).  We could free up 4 finger actions to allow other extensions to use that (e.g. [Gesture Improvements](https://extensions.gnome.org/extension/4245/gesture-improvements/) etc.

**Comment by jtaala** [comment]
I'm open to adding a user preference toggle to disable the workspace gesture (and maybe even the 3-finger swipe up gesture for Gnome overview).  Note, this would just be for gestures though - not disabling workspaces entirely (i.e. users could then disable PaperWM workspace switching keybinds if they really wanted).

**Comment by Polisson** [comment]
Forgive further ambiguity and inaccuracy. Yes, I just meant "disabling workspace stack switching". It is quite quirky with current Gnome's effects. Also, freeing up 4 finger actions would be really great way to allow 3-parties to work with PaperWM and provide built-in features to Gnome.

My point of view, realized because of the previously mentioned extension **V-shell** - it has the ability to set vertical layout of desktops. It also "rotates" behavior of gestures (3-finger vertical are switching desktops, 3-finger horizontal Overview and AppGrid). 
Current behavior: When set along with PaperWM, V-Shell allows switching desktop to the next one (because 3-finger up is free, and means 'Next desktop'). Reverting to 'Previous desktop' is obscured by _workspace stack_. Horizontal gestures (3&4 finger) are also obscured by PaperWM, so I completely lose the ability to trigger Gnome's Overview etc.

**Comment by jtaala** [comment]
> My point of view, realized because of the previously mentioned extension **V-shell**

Ah - I see.  Well, we could add some dconf user settings (that can eventually be added to the PaperWM settings app), I suggest the following:
- `gesture-disabled` (`true`, `false`): disable all PaperWM gestures (i.e. so user's can either have no PaperWM gestures and/or use something else);
- `gesture-swipe-horizontal-fingers` (`0` for disabled, otherwise`3` or `4`): sets the fingers to use for PaperWM left/right tiling swiping (moving windows left/rifht);
- `gesture-workspace-stack-switch` (`0` for disabled, otherwise`3` or `4`): set the current PaperWM `swipe-down` action to be disabled or 3 or 4-finger swipe;
- `gesture-overview-fingers` (`0` for disabled, otherwise`3` or `4`): set the current PaperWM `swipe-up` action (Gnome overview) to be 3 or 4 fingers in paperwm;

I think that will cover most use-cases for gestures?

**Comment by jtaala** [comment]
> It is quite quirky with current Gnome's effects.

Can you give some examples of these quirks?  I haven't observed any.  It seems the main issue here is extension conflicts with **V-shell**.  That is, **V-shell** assumes standard gnome swiping behaviour, whereas PaperWM doesn't work like standard Gnome.

Hence, I assume the quirks you're seeing are due to PaperWM with V-shell.  I've implemented the gesture disable options in a a branch and have been testing - ~~and even with these disabled there's still issues with **V-shell** and **V-shell**'s way of workspace switching.~~ _ha.. so this is now working pretty well..._

Extension specific conflicts are generally out of scope for PaperWM (there's just too many extensions to be able to address specific extension conflicts).

In any case, I'm still planning on adding the aforementioned gesture options - however, your mileage may vary in how other extensions interact with PaperWM (even with these options).

PaperWM is open-source though, and we'd happily accept PRs that resolve specific issues with other extensions if you find a way to address those extension conflict issues.

**Comment by jtaala** [comment]
> Is this still in consideration? I'd like to disable workspaces altogether

We're not considering disabling "workspaces altogether". however, adding options to disable workspace switching gestures (so you don't accidentally swipe it)  can be done.

**Comment by jtaala** [comment]
Hey all,

I've now implemented a branch with these gesture options.  Please give it a test:

```
git fetch --all
git checkout add-gesture-options
```
And then logout/login.

Once logged in, run any of the options from a terminal:

To enable gestures: `true`, `false`, e.g. to disable them (note this is a convenience method and disable all gestures except `gesture-horizontal-fingers`:
```
dconf write /org/gnome/shell/extensions/paperwm/gesture-enabled false
```

Set horizontal swiping to: `0` for disabled, otherwise`3` or `4`, e.g. to set to four fingers
```
dconf write /org/gnome/shell/extensions/paperwm/gesture-horizontal-fingers 4
```

Set `workspace stack switching` fingers:  `0` for disabled, otherwise`3` or `4`, e.g. to disable that gesture:
```
dconf write /org/gnome/shell/extensions/paperwm/gesture-workspace-fingers 0
```

~~To enable/disable the gnome overview gesture in PaperWM (3-finger swipe up): `true`, `false`~~

~~dconf write /org/gnome/shell/extensions/paperwm/gesture-overview false~~

**Comment by jtaala** [comment]
@Polisson 

Can you test this with **V-shell**?  The options you should run for V-shell should be (after checking out the branch):

```
dconf write /org/gnome/shell/extensions/paperwm/gesture-enabled false
dconf write /org/gnome/shell/extensions/paperwm/gesture-horizontal-fingers 4
```

Which disables PaperWM gestures but sets horizontal-swiping to four-fingers (to avoid a clash with V-shell's 3-finger swipe for Gnome overview).

Cheers,

Jay.

**Comment by jtaala** [comment]
Hey all, I'm now largely happy with this #596 (pull the latest on that branch to test out).

```
dconf write /org/gnome/shell/extensions/paperwm/gesture-enabled false
```

running the above command will cause paper to defer to default gnome behaviour for gestures.  I've implemented some animation fixes to support this - so default 3-finger workspace switching looks correct now, (@Polisson) including if using v-shell.

This allows PaperWM to work better with other gesture control extensions.

**Comment by jtaala** [comment]
Hey all, this is now merged into `develop` branch, and will make it way into the next release.

Please give this a test.

**Comment by jtaala** [comment]
Now released.

See the new touchpad gestures section in README.md: https://github.com/paperwm/PaperWM#touchpad-gestures
