### ISSUE TITLE
Mass window closing, like on browsers.

### ISSUE THREAD

**Issue by ripefig** [paperwm/PaperWM#120]
Again apologies if out of scope, but I think there is a use case for closing windows in workspace en-masse, the same way you can do on browsers.

Examples:

1. Close all windows [or all windows of a class] to the left/right of current window. Useful for tabless browsing - given that PaperWM doesn't leave much room for tabs inside windows.
2. Close all windows in workspace (destroy workspace).

**Comment by olejorgenb** [comment]
I think #53 would solve this nicely. Ie. select all to the left/right could be done quickly by pressing and holding `</>`. Issuing a close on a selection would close all windows in the selection.

I'm not sure what you mean by "doesn't leave much room for tabs"?  That's up to the applications.

Closing **all** windows in a workspace works by pressing and holding `<Super>Backspace`. Ie. the action triggers again on key-repeat. (though we miiight change that (if technically possible) since it's source for mistakenly closed windows)

**Comment by ripefig** [comment]
This partly addresses the issue, I agree. A single action, like on browsers, still has the advantage of fewer keypresses/clicks - so it might be something to put on the backburner.

**Comment by olejorgenb** [comment]
> You mean it can accidentally close multiple workspaces on key repeat?

No just multiple windows. The close action doesn't continue to the next workspace. 

I haven't really considered the repeat behavior before - mutter (the gnome-shell "backend") triggers actions on key-repeat and I'm not even sure if that's controllable (without a hack).

I've used the extension for well over a year now and can't remember mistakenly closing a window due to the repeat though. But I know some WM's special cases repeat behavior of the close action (eg. notion/ion3).

**Comment by ripefig** [comment]
Oh in that case I would consider implementing a single action to close an entire set of windows (e.g destroy workspace). This could make tabless browsing possible on paper WM, for example. The current functionality more or less does the job, but it's a little less convenient.

**Comment by olejorgenb** [comment]
I agree that such action is useful for certain workflows, but we try to keep a slim core feature set atm. 

Implementing a crude version of the action is simple (though no future API guarantees are given):

```javascript
    var Keybindings = Extension.imports.keybindings;

    Keybindings.bindkey("<Super>d", "close-workspace", (mw) => {
        if (!mw) {
            return;
        }
        let space = Tiling.spaces.spaceOfWindow(mw);
        for (let col of space) {
            for (let metaWindow of col) {
                metaWindow.delete(global.get_current_time());
            }
        }

        // Uncoment to also remove the workspace
        // global.workspace_manager.remove_workspace(space.workspace, global.get_current_time());

    }, {activeInNavigator: true})
```

Put the above in `~/.config/paperwm/user.js` inside the `init` function (after the existing code)

Note you might not want to remove the workspace since we don't have a convenient way to quickly create new workspaces. That is on the plan though.

**Comment by ripefig** [comment]
You could just manage workspace with Gnome overview though, correct?

**Comment by olejorgenb** [comment]
Sure :)

But don't think you can create new workspaces from the overview if you use the static workspace settings?

**Comment by jtaala** [comment]
New features that allow managing multiple windows at once (including closing them all): #808.

**Comment by jtaala** [comment]
Closing as #808 adds the ability to mass close selected windows.
