### ISSUE TITLE
Restore gnome shell settings script has empty values

### ISSUE THREAD

**Issue by llandsmeer** [paperwm/PaperWM#121]
Hi, great extension! Sadly, the generated `restore-gnome-shell-settings-*.sh` scripts didn't contain the previous values on my setup and now it wont reset to the backup. Not that that is a huge issue, but might be useful to fix.

Running something like `dconf read /org/gnome/shell/overrides/workspaces-only-on-primary` also gives an empty output, if that helps. I have no idea why this happens or what might cause this. I'm running a pretty vanilla Ubuntu 18.04.2, GNOME Shell 3.28.4, PaperWM commit `393365e`.

File contents (with single whitespace at eol):
```
dconf write /org/gnome/mutter/auto-maximize 
dconf write /org/gnome/shell/overrides/workspaces-only-on-primary 
dconf write /org/gnome/shell/overrides/dynamic-workspaces 
dconf write /org/gnome/shell/overrides/edge-tiling 
dconf write /org/gnome/shell/overrides/attach-modal-dialogs 
```

**Comment by olejorgenb** [comment]
Thanks :) 

Sorry about the broken script - seems like `dconf read` doesn't output values when the value is "use default".

Since all keys have empty values in the restore script that indicates your previous settings was the default settings. (I can't get dconf to set the value to the special value "use default", so I think you'll have to use dconf-editor to reset the settings :/ )

It strange that `/org/gnome/shell/overrides/workspaces-only-on-primary` did not get set to `false` though.

**Comment by llandsmeer** [comment]
Great, thanks, can confirm it works!
