### ISSUE TITLE
Can't make window fullscreen with dual monitors

### ISSUE THREAD

**Issue by egegunes** [paperwm/PaperWM#134]
Making a window fullscreen works as usual with a single monitor but with multiple monitors top bar doesn't disappear. I made a screencast to demonstrate: [Gfycat](https://gfycat.com/delayedrevolvinganteater)

Edit: If I disable "show top bar" from workspace settings, problem doesn't occur.

**Comment by hedning** [comment]
Hmm, weird it seems to triggered here via the fullscreen signal:
https://github.com/paperwm/PaperWM/blob/5a8b1c29b0a882b023afa25c9151aaa08e38d7b9/tiling.js#L2330-L2334

So that obviously doesn't make much sense as we're checking if the window is fullscreen, but I've had problems with the fullscreen signal reporting weird values before so :man_shrugging:.

Anyways it does look like obsolete code so it should be okay to remove. I'll test it out a bit and remove it if I don't see any problems.
