### ISSUE TITLE
Add option to set activity overview background to match current workspace

### ISSUE THREAD

**Issue by avarsh** [paperwm/PaperWM#147]
Currently, the activities overview and application launcher uses the default background, which has a slightly jarring visual effect when transitioning between the overview and workspace. If technically possible, it may lead to a smoother experience and a more seamless transition if the option to set the activities background to the current workspace's wallpaper is present.

**Comment by olejorgenb** [comment]
A concern is performance of changing the background (since the action already is expensive) though I don't think we've actually tried it. The alternative is monkey patching the activity overview further.

Setting the default workspace background to the gnome-shell background is a quick-fix. (related: https://github.com/paperwm/PaperWM/issues/122#issuecomment-504524005)

**Comment by hedning** [comment]
Right, this is implemented now (though note we do not support using «animated/changing» backgrounds yet).
