### ISSUE TITLE
Multimonitor support

### ISSUE THREAD

**Issue by olejorgenb** [paperwm/PaperWM#17]

**Comment by hedning** [comment]
Commit 51e95bf998e061a83d3a00baca1eab18a77d3957 fixes workspaces for the primary display. Having a monitor on the left or right of the primary doesn't really work practically as you get the stack protruding onto the monitor, this can potentially be fixed by setting some clip values.

Also, I'm not having much luck in setting `/org/gnome/shell/overrides/workspaces-only-on-primary` to false.
