### ISSUE TITLE
Crashes while opening wallpaper picker or color picker in paperwm extension settings on Manjaro Gnome

### ISSUE THREAD

**Issue by Caenhorn** [paperwm/PaperWM#200]
Crashes while opening wallpaper picker or color picker in paperwm extension settings on Manjaro. Also, happens while opening sub-windows in different other extension settings. Tested on Manjaro Gnome 18.1.3 on two different machines.
Distribution: Manjaro Gnome 18.1.3
Captured a log with fresh boot and a crash reproduced shortly after:
[journalctl-gnomeshell.log](https://github.com/paperwm/PaperWM/files/3868636/gnome-crash.log)
PaperWM version is at commit 697f025c55491a0b351e50fc7fc5231d4aaa1484 (latest at the moment of submitting)

**Comment by Caenhorn** [comment]
Also, need to mention, that when I open extension settings, the window doesn't go into horizontal stack of windows, but rather floats in the middle of display.
![Screenshot from 2019-11-20 12-32-40](https://user-images.githubusercontent.com/33941345/69231554-f235d880-0b91-11ea-8237-b5db3700f5b8.png)

**Comment by hedning** [comment]
Right, could reproduce that, the culprit was 1c5779116b5aca641ce114f04ea3bc704ba8e30e. Not entirely sure how that caused it, but looks like an edge case where we would enter an infinite loop when opening new windows from scratch windows (at least for the prefs gui). 

 > Also, need to mention, that when I open extension settings, the window doesn't go into horizontal stack of windows, but rather floats in the middle of display.

This is intended behavior. The preference gui is a short lived window and can reflow the tiling by changing eg. the window-gap, so I feel having it float by default is a sane default. (note it tiles by default in wayland, due to an upstream bug which makes some menus unusable in `always-on-top` windows).
