### ISSUE TITLE
[Feature Request] Padding for windows on either end of the stack

### ISSUE THREAD

**Issue by necopinus** [paperwm/PaperWM#209]
Any chance there could be an option to add padding to the far left and right ends of the window stack, similar to how the **Bottom margin** property adds padding to the bottom of the screen? Right now, the very first and very last windows sit right on the edge of the screen, which is somewhat jarring.

Ideas:

1. Re-use the **Bottom margin** property for either end of the window stack.
2. Have separate left/right margin properties.
3. Apply the **Horizontal margin** property to the far ends of the window stack, not just when there's another window next to the current window.

Option **(1)**  has the advantage of automatically providing consistent left/right/bottom padding, but option **(2)** seems more consistent with the current settings presentation.

**Comment by necopinus** [comment]
Here's a short video showing how the windows on either end are jammed right up against the screen margin, while the **Horizontal margin** just gets applied internally: https://drive.google.com/file/d/1R6Bz5AE8W6XA-ZW4p2q67DkZ8xeY3nAc/view

**Comment by hedning** [comment]
Yeah, this is intentional, and the «Horizontal margin» naming is confusing as it implies a consistent margin. There's been other people who want this option too, so it should probably be done :) 

So the idea with the current `horizontal-margin` is having a scroll margin like in text editors. That's a much better name tbh.  So it might make sense to rename horizontal-margin to scroll-margin, and then introduce a left/right-margin.

Not entirely sure if it's worth it to have distinguish between the left and right, but having a dock on eg. the left is an argument for at least.

**Comment by liquidev** [comment]
Any news on this? I found a workaround by centering the window, but then that leaves me with too much free space to the left or right of it, which is quite jarring too.

**Comment by hedning** [comment]
Managed to misclick the close button :p

I'd accept a PR on this introducing an explicit `scroll-margin` so `horizontal-margin` can be applied consistently. Though I still think it should default to `0` to preserve the start/end hint.

A bit busy with work/life, and this isn't really on the top of my personal wish list (will have to update for gnome 3.40 soon, so most of my paperwm time will probably go towards that).

**Comment by jtaala** [comment]
This exact functionality was a recent PR (#467) for a while, but was ultimately closed in favour of #488.

There's a long history in #364 with some related commentary (along with comments in #488).

Closing this issue now.
