### ISSUE TITLE
Cycle Through Useful Window Heights not working

### ISSUE THREAD

**Issue by pyro57** [paperwm/PaperWM#219]
I see in the keybindings settings that Cycle through Useful Window Heights.  I would like to be ale to divide my screen by height and width, however I can't adjust the height and cycling through useful heights seems to do nothing.

**Comment by hedning** [comment]
So the tiling in paperwm is layed out in columns. Each column can have windows tiled vertically. We do not support arbitrary tiling, and it's unlikely we'll ever will tbh. 

As such, cycling the height will only work when a column has more than one window, or floating. You can «slurp» the window to the right into the current column with `Super+I`.

There's also wip PR that make the column height free (ie. the window is anchored to the top bar, but the height can otherwise be changed as you please). @olejorgenb uses this on a large monitor, might be what you're after.

**Comment by pyro57** [comment]
the Window + I seems to do something similar to what I want, I'll live with that for a bit and see what I think, Thanks!
