### ISSUE TITLE
Notifications appear in front of fullscreen windows

### ISSUE THREAD

**Issue by shibotto** [paperwm/PaperWM#221]
I tried this in a clean up-to-date Fedora 31 VM, to rule out potential misconfigurations of my home directory or distro.

Without and with PaperWM demonstration:
![paper](https://user-images.githubusercontent.com/3816409/72149821-47c57f00-33a4-11ea-973f-44e40c2c35a7.gif)

I also tried restarting the Shell and logging out/in after enabling the extension, but the problem persists.

**Comment by hedning** [comment]
Gnome-shell hides notifications if there's any fullscreen window on the active workspace on the primary monitor. 

Since fullscreen windows can be entirely hidden in paperwm (ie. scrolled away to the sides) this isn't workable behavior. As such we've monkey patched the code to not care about fullscreen windows at all.

Now, we could change this so it will hide notifications if the selected window on the primary monitor is fullscreen. That would stick closer to the default gnome shell behaviour.
