### ISSUE TITLE
Installation instructions in README incorrect

### ISSUE THREAD

**Issue by creikey** [paperwm/PaperWM#230]
On using `gnome-extension-tool` to install the extension, it does not install and instead prints: 

```gnome-shell-extension-tool is deprecated, use gnome-extensions instead```

After reading the help for `gnome-extensions` and trying to use `gnome-extensions install paperwm@hedning:matrix.org` without success, I am not immediately certain of how to install this plugin.

**Comment by hedning** [comment]
While deprecrated, `gnome-shell-extension-tool` still works,. Unfortunately gnome-shell sometimes (or always?) doesn't notice the extension being in the correct location without a restart (`alt+f2` + `restart` if using X11). If there's no effect then the deprecation warning will be confusing :/ There's a PR to change the instructions to use `gnome-extensions`, but we haven't merged since 

To install you'll need to either run `./install.sh` or clone into the correct directory as described in the readme.

If you really want to avoid a restart I'd try to verify that `gnome-extensions enable paperwm@hedning:matrix.org` dosen't work. If not this might work (untested):
- In the paperwm directory run `gnome-extensions pack`
- `gnome-extensions install paperwm@hedning:matrix.org.shell-extension.zip`
- `gnome-extensions enable paperwm@hedning:matrix.org`

Happy to hear back if any of that works, as the installation could absolutely be a bit smoother.

**Comment by hedning** [comment]
OK, `gnome-extensions pack` doesn't work as it doesn't pack the required files.

**Comment by hedning** [comment]
Made some improvements to the install script in #231. it will now do the correct work to enable paperwm without any restarts :)

**Comment by hedning** [comment]
OK, the installer should now enable paperwm and set recommended settings if wanted.
