### ISSUE TITLE
Fullscreen: when switching between monitors, top bar comes back.

### ISSUE THREAD

**Issue by jtagcat** [paperwm/PaperWM#242]
If your app goes full screen on the same display, all is fine. Until you switch to an another display and back to the one with the fullscreen app.
When you launch the app on display a and move it to display b, the top bar will be present as well.
![image](https://user-images.githubusercontent.com/38327267/74092530-44193b00-4abd-11ea-8909-26ca15b124c4.png)
It is probably caused by the weird top bar behavior (top bar is shown only on focused display) (when I actualy only want it always on the main display).

**Comment by hedning** [comment]
Yeah, this one i a bit annoying. I looked into it a few days ago. IIRC the workspace switch makes gnome shell check if it should show the top bar. Since there's no windows in the active workspace on the primary monitor gnome shell thinks it should show the top bar.

We'll basically need some more logic in the top bar show signal, or do some other monkey patching I think.

**Comment by hedning** [comment]
OK, that was a lot simpler than I'd remembered. Should hopefully be fixed by 10011c98c346a1997a17239fffbd8f19ed3d80c7

**Comment by jtagcat** [comment]
How does one upgrade the installation in place? I did notice any git where it was cloned by the install script.

**Comment by hedning** [comment]
The git repo is symlinked to the correct location, so you can just pull from there.

For it take effect you'll need a restart (gnome-shell doesn't support reloading extensions in place, though we've made an [emacs mode](https://github.com/paperwm/gnome-shell-mode/) which can do it). So that unfortunately means logging out if you're using wayland.

**Comment by hedning** [comment]
Made branch to test out keeping the top bar on primary: https://github.com/paperwm/PaperWM/issues/143#issuecomment-585767378

**Comment by jtagcat** [comment]
Tested, works. I'd indeed rather have it only on primary.
