### ISSUE TITLE
Moving a window over multiple workspaces picks up one window form each workspace i passes

### ISSUE THREAD

**Issue by Pajn** [paperwm/PaperWM#245]
If I have three workspaces with the set up
[Firefox,Firefox]
[Gnome-terminal]
[Nautilus]

and want to move the second firefox to the bottom (next to nautilus) with `ctrl+super+page down` it also picks up gnome-terminal on the way down so I end up with:
[Firefox]
[]
[Nautilus,Firefox,Gnome-terminal]

**Comment by hedning** [comment]
Yeah, you'll have to release `ctrl` mid flight. It's not the most intuitive, but we never implemented a drop window on `ctrl` release. So we went with holding ctrl down meant picking up more windows (as that wouldn't really be possible otherwise).

Now, `super-t` makes it possible to pick up more windows now, so we should probably do a re-design here tbh.

**Comment by jtagcat** [comment]
I agree with both of your statements.
I find it super annoying, that it picks up a seemingly 'random' window. 2-3 times a day I end up needing to reorganize 5-6 windows due to not noticing this (and being used to the default gnome behavior of one-window-at-a-time).

The picking up with a separate hotkey makes sense, as you can actually pick what you are picking up (else you have to have the windows you want to pick up active in all workspaces, needing setup).

**Comment by jsravn** [comment]
I agree this makes workspace management a real pain. There isn't a way to quickly move things to the correct workspace with keybindings it seems. I've resorted to using the overview and manually dragging windows for now.

**Comment by hedning** [comment]
`Super-T` picks up a window[s] which you can then move freely. But yeah, `Super+Ctrl+above_tab/Page_Up/Down` doesn't work well in it's current form, and we should probably change it back.

**Comment by jsravn** [comment]
Super-T works pretty well - wasn't familiar with that yet. Thanks!

**Comment by jtaala** [comment]
Fixed by #443.
