### ISSUE TITLE
Curious: 3 Finger Swipe "Up"

### ISSUE THREAD

**Issue by rawkode** [paperwm/PaperWM#263]
This seems to Zoom. I can't find it documented.

Help?

**Comment by hedning** [comment]
It's just meant as a an indicator that you can't there's nothing «above» the current workspace (like the springy scoll edges on smartphones). 3-finger up/down navigates the workspace mru, so at the start there's only one meaningful direction (assuming no cycling).

We played with the idea of centering the zoom on the pointer, as that would make it useable as a quick zoom, but haven't done anything with it yet.

In the future 3-finger up would work well to pull up the overview, but I'd want it to work smoothly (ie. follow fingers) so that probably won't happen until we do more work on the overview.

As a side note, in gnome-shell 3.36 it's now possible for us to use 4-finger swipes too, so it might make sense to use that to navigate through workspaces in their static order. So 4-finger would be akin to `<Super>Page_Up/Down`, while 3-finger would be `<Super>above_tab`. The ordered workspace navigation could do with an overhaul anyway so.

**Comment by rawkode** [comment]
Activating Overview mode or zooming into the cursor would be fantastic :tada:

**Comment by rawkode** [comment]
@hedning Is there a branch for Zoom to pointer? I'd like to help contribute, I think that would be a great feature.

**Comment by hedning** [comment]
Nope, haven't made a prototype as far as I know. The relevant code is here: https://github.com/paperwm/PaperWM/blob/b33f2d859dc0eaced1d338e336928fa78943e32d/gestures.js#L342-L349

This just scales the space in proportion to its `y` position.

The logic required for zoom to pointer would be `selected.actor.y == 0` and `dy > 0`. At which point the space's `pivot_point` would need to set to the pointer and we'd increase the scale in proportion to `dy`.

Then if `dy < 0` and `scale > 1` we'd decrease the scale until we hit `1` and we'd need to reset the pivot point and start moving the space normally.

The gesture code isn't super pretty, but hopefully that made sense.

**Comment by paradajz** [comment]
Having the ability to activate overview with three fingers up would be amazing (to be honest I find this "zoom" gesture quite useless). I would also be willing to pay you for this since I love PaperWM so much - it's best computing experience I ever had.

**Comment by olejorgenb** [comment]
(another issue requesting desktop zoom: #238)

**Comment by jtaala** [comment]
I think I would also like an action for overview with 3-fingers up.

For #238, I think overview would be more useful(?).

**Comment by jtaala** [comment]
Hey @paradajz & @rawkode,

See PR #552 which implements gnome overview for 3-finger swipe-up while keeping the current behaviour for 3-finger swipe-down... e.g. up does overview mode and down does PaperWM workspace preview mode.
