### ISSUE TITLE
super + and super - does work very sporadically with gnome-terminal

### ISSUE THREAD

**Issue by Pajn** [paperwm/PaperWM#277]
The new shortcuts for resizing a window are great and really smooths out the workflow!  However, I'm having problem with them on gnome-terminal specifically where they most times does not at all or does a strange resize.

I have only tested the Wayland session so far but other native Wayland apps works fine.

My very unknowledgable guess is that it has a problem with gnome-terminals unwillingness to be resized to any size and instead want the window size to match the character grid. It also demonstrates this with not being as tall as other windows.

xdg-shell has properties to tell a window that it's tiled and in such cases I think that the window must respect the size it's given https://cgit.freedesktop.org/wayland/wayland-protocols/tree/stable/xdg-shell/xdg-shell.xml#n800. I have no idea if it's possible for a gnome extension to set those on windows but it could be a potential solution.

This issues seems related: https://github.com/emasab/shelltile/issues/30, https://github.com/gTile/gTile/issues/86

**Comment by olejorgenb** [comment]
Yes, this is most likely due to gnome-terminal resizing in increments. Ref #187. It is probably _possible_ to work around, but we have not found the motivation yet. (My suggestion is to use Tilix instead :))

The interface expose to extensions seems in general to be the intersection between wayland an X11, so I doubt it's much we can do yet. If we set the windows as tiled I'm quite sure the position and height is forced)

**Comment by Pajn** [comment]
Tilix seems to work quite well as a workaround, thank you!

**Comment by hedning** [comment]
Hmm, setting gnome-terminal to maximize vertically does fix it, not only in the height direction but also width. Though that only works for single window columns, and it makes client sides title-bars square, but not server-side. So there's some issues with getting the styling consistent.
