### ISSUE TITLE
Horizontal 3-finger trackpad swipes do nothing

### ISSUE THREAD

**Issue by crispinb** [paperwm/PaperWM#292]
I've tried this on two multitouch trackpads and get the same results (or lack thereof) - nothing happens.

**Comment by Pajn** [comment]
It works here. I think you need the Wayland session though, are you using that or Xorg?

**Comment by crispinb** [comment]
Wayland  (I normally use xorg, but switched to try this out). Vertical swipes are working after a fashion.

**Comment by crispinb** [comment]
Correction - that description wasn't quite right. Swipes seem to do something, but I'm not quite sure what. After a swipe, an overlay showing a directory I have on the desktop appears at the top right, and the workspace doesn't respond to further trackpad or mouse events, until I've done something at the keyboard.

**Comment by Pajn** [comment]
That sounds very strange. Is it possible that you have another extension that overrides the geasture? To my knowledge there is no desktop/folder overlay in PaperWM.

**Comment by crispinb** [comment]
That's odd then - any folders I have on the desktop always appear transiently on top of other windows while I'm switching workspaces (using the keyboard). I had just assumed that was expected behaviour (though I had no idea why).

I use a few extensions but none put anything on the desktop. I've tried disabling all but PaperWM, to no different effect.

**Comment by Pajn** [comment]
>I use a few extensions but none put anything on the desktop

Well, gnome doesn't support desktop icons, so _something_ does :) Are you using Ubuntu? They ship with bundled extensions that show desktop icons which seems like the suspect if you have not installed any such extension yourself.

If so you should be able to
```
sudo apt install gnome-session
```
and select Gnome instead of Ubuntu when you log in to get a more vanilla experience. You can log out and select Ubuntu again if you want so there's no permanent change just to test.

If that works then it's at least an extension clash. If it's PaperWM or Ubuntus desktop icons extension that needs a fix I have no idea about though...

**Comment by hedning** [comment]
Yeah, that's a known interaction with the desktop-icons, and specifically ubuntu. If I understand correctly disabling desktop-icons should just work on ubuntu-19.10, but it's more sticky on ubuntu-19.04 (not sure if there's a proper solution apart from what @Pajn noted).

**Comment by crispinb** [comment]
OK yes that's it. Odd as I never had the desktop-icons extension enabled (it was mere accident that I somehow ended up with a folder there). But anyway, using the vanilla session works as you suggest. Thanks.
