### ISSUE TITLE
Top bar disappears when moving between monitors

### ISSUE THREAD

**Issue by elshimone** [paperwm/PaperWM#308]
There appears to be an extension conflict between PaperWM develop branch (404d50c41675f0169018ce8ecaa13cb589825389) and Dash to panel v37.

I have "Make top bar follow montior focus" off in PaperWM.  

In dash to panel, I have "display the main panel" on set to default, and "Display panels on all monitors" set to off.  I have played around with the options a bit to see if I can get a combination which works, but to no effect.

You can see when I move my cursor from the primary to the secondary monitor on the left, the top bar disappears.

GNOME Shell 3.36.1
simon@tachikoma ~/d/PaperWM>                                            (PaperWM) 20:30:53

They are both great extensions, FWIW I have disabled dash to dock for now :)

![paperwm_dash_to_dock_trimmed](https://user-images.githubusercontent.com/698207/82598406-89600500-9ba2-11ea-87e1-02d2daa12e1d.gif)

**Comment by hedning** [comment]
Right, «top bar follows focus monitor» still moves the top bar, but always to the primary monitor: https://github.com/paperwm/PaperWM/blob/b33f2d859dc0eaced1d338e336928fa78943e32d/topbar.js#L624-L633

I'd guess this issue would be fixed by leaving the top bar alone in the above code, and only move it to the primary monitor when `topbar-follow-focus` is turned off:
https://github.com/paperwm/PaperWM/blob/b33f2d859dc0eaced1d338e336928fa78943e32d/topbar.js#L540-L549

**Comment by elshimone** [comment]
Thanks for the pointer, this fixes it for me, but I don't completely understand what the topbar_follow_focus setting should do.

**Comment by jtaala** [comment]
Fixed by #309.
