### ISSUE TITLE
More prominent visual hint when switching windows?

### ISSUE THREAD

**Issue by exp2ipi** [paperwm/PaperWM#321]
One usability issue I am encountering with my configuration is that when switching windows via `Super-,` or `Super-.` it's not clear what is the active window. This is particularly bad if the gap is reduced to 0 and you are switching between windows of the same type.

Is it possible to optionally draw something like a red border around the selected window (only while the `Super` key is held down)?  Alternatively, is it possible to display a border around the window in the minimap (the same way a border is drawn in the minimap when `Alt-Tab` is invoked)?

**Comment by hedning** [comment]
The minimap inherits the window gap, which it really shouldn't (it's a simple fix in minimap.js).

Making a specific border when navigating windows isn't probably something we'll do, as that's to a large extent why the window highlight is there.

**Comment by exp2ipi** [comment]
@hedning just to clarify: I am looking for minimap behavior like the one illustrated in the gif here: https://jvns.ca/images/paperwm.gif -- would the minimap.js you are talking about achieve this?

**Comment by hedning** [comment]
Yep the highlight in the minimap also scales with the window gap (IIRC the idea was making the map realistic, which we've mostly moved away from).

So in https://github.com/paperwm/PaperWM/blob/develop/minimap.js,  we should use a fixed constant instead of using `prefs.window_gap` (I'd go for 20px as that's in practice the default at the moment). It's a super simple fix, that I for some reason haven't gotten around fixing.

Yeah, you won't really see the window highlight at zero window gap.

**Comment by exp2ipi** [comment]
Brilliant, messing with the gap in minimap.js does the trick!
