### ISSUE TITLE
Replace preview tiles in PreviewNavigator with a properly scaled minimap

### ISSUE THREAD

**Issue by hedning** [paperwm/PaperWM#33]
The minimap should have windows in the horizontal direction, and optionally show workspaces in the vertical direction, while pseudo-focus should always remain within the center.

The left/right stack should spread out to a full minimap when selecting a workspace, and recede back in when it's unselected.

Very ugly mockup:
![image](https://user-images.githubusercontent.com/71978/30861368-ff676480-a2b9-11e7-974d-20a0a2a2e9ca.png)

**Comment by olejorgenb** [comment]
It's tempting to reuse `Workspace.WindowClone`, but so far the mismatch seems a too large. The position of the window clone is updated by itself for instance (with non-obvious results when attached in the minimap atm). We probably don't want such position updates since stacked windows positions should _not_ correspond.

Transients doesn't seem to to handled out of the box either (there's methods for adding them though)

**Comment by olejorgenb** [comment]
The overview window previews (`Workspace.WindowClone`) use a completely separate actor [1] for the chrome (border on hover, etc). It's positioned by syncing the size (the transformed size) and position with the clone.

Not sure why it's done like this, but one advantage is that the chrome can operate in "unscaled dimensions".  If one simply place a clone inside a container X, set a border on X and scale X (or its parent like we do now) the border is of course also scaled. It's not obvious that all such chrome should follow the overall scale of the minimap. With this approach it's simple to keep the layout independent of the chrome size (not that this is a very hard problem).

Another way around this might be to scale the clone directly and let the container report its size as the clone's _transformed_ size. Clutter seems to discourage this though (?).

[1] `Workspace.WindowOverlay`

**Comment by hedning** [comment]
This is somewhat implemented now.
