### ISSUE TITLE
Topbar turns transparent when activating PaperWM

### ISSUE THREAD

**Issue by vincentmathis** [paperwm/PaperWM#344]
![Before activating PaperWM](https://user-images.githubusercontent.com/33002126/96957587-92a32400-14ea-11eb-81e1-61319e18d23a.png)
![After activating PaperWM](https://user-images.githubusercontent.com/33002126/96957593-99ca3200-14ea-11eb-99b5-70667e1336ab.png)

**Comment by hedning** [comment]
Yeah, this is intended (meant to show case the workspace color), but since transparency can be a bit tricky it isn't guaranteed to work well with all themes and backgrounds.

`Main.panel.actor.set_style('')` in your `user.js` enable function should probably be decent local fix.

Open to a PR to make it optional.

**Comment by Thesola10** [comment]
@hedning I get it, but are you sure it's within the scope of PaperWM to make the topbar transparent? I'm having issues on launch with Dash to Panel's handling, and it can cause conflict with more extensions

**Comment by hedning** [comment]
> I get it, but are you sure it's within the scope of PaperWM to make the topbar transparent?

Yeah, I can absolutly buy that argument, and I'll happily accept a PR that makes top bar transparency configurable :)

**Comment by raiguard** [comment]
Bump. I would like the top bar to be more transparent than it currently is. It's strange that PaperWM modifies the top bar style at all, I don't see what you mean by "workspace color") when you can clearly see it around the borders of the windows already.
