### ISSUE TITLE
Housekeeping the list of issues, and gnome-version development?

### ISSUE THREAD

**Issue by johnmee** [paperwm/PaperWM#422]
Two for the price of one...

## Issues

Now that its all back in one place, there appear to be a lot stale, or not so stale?, issues; not yet as many open issues, as closed, but getting there.  Perhaps it is time to enlist some more help and/or grant permissions to enable someone go through them all?  Or just declare them all closed, and invite people to reopen the ones they care about.

## Gnome Versions

There appears to be a lot of work generated by supporting, or trying to, many versions of Gnome.  Might one suggest a strategy be adopted for handling versioning?   For example "develop" could follow the "main" branch of Gnome-shell, and branch accordingly whenever they release.

**Comment by smichel17** [comment]
On gnome versions, that's what has been done. The `develop` branch supports gnome 42, and there are branches/tags with the last version that supported gnome 40 and 32-38, respectively.

On issues, I think it's fine. There are several people who use PaperWM every day and don't want it to break, so the issues they personally run into are likely to be fixed. However, as far as I know there is nobody **actively** maintaining PaperWM, in the sense of looking through other people's reported issues in order to fix them. So, having messy issues is not really hurting anybody.

I would like to look through the issues and clean up duplicates, to make it easier in case the speed of development picks up again. However, this is a very low priority for me; it's just a thing I might do some day if I feel like it. In the meantime, if you or someone else want to look through and comment about which ones are duplicate or out of date, I can close them. I'm subscribed to the repo, so you don't need to mention me.
