### ISSUE TITLE
Fedora packaging

### ISSUE THREAD

**Issue by gombosg** [paperwm/PaperWM#439]
Hey! I'm packaging this for Fedora.
BZ: https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2140404

Some notes: 

- I think that the schemas file should be renamed from `scrollwm`. #440 
- I'd _really_ appreciate a reliable versioning scheme and Github releases for this. It's OK to version along with GNOME versions, but it makes packaging much, much easier if a Github release (or at least a Git tag) is created. Otherwise I won't know when to release a new version.

**Comment by smichel17** [comment]
There is an issue with choosing a versioning schema right now, which is that there is not anyone to choose when to do releases. I am keeping the project on life support (see https://github.com/paperwm/PaperWM/issues/407) but even now I'm doing more than I originally planned (because I have `Maintainer` access to the repo, not `Admin`, so I can't currently add new maintainers). So we effectively have a rolling release model right now.

There's also the issue of the current software being moderately buggy on recent Gnome versions. Certainly usable, but if it were my main project, I wouldn't want a full release in the current state (definitely appropriate for a pre-release though). I'm not sure how you'd like to reflect that in Fedora packaging. The latest "stable" release would be [38.2](https://github.com/paperwm/PaperWM/releases/tag/38.2), which still needs someone to write a changelog entry (https://github.com/paperwm/PaperWM/issues/416).

I think the few historical tags have followed an X.Y schema, where X follows the gnome version and any release can contain breaking changes (whatever that means in the context of a GUI application). I think X.Y.Z would also be OK, where Z would be bugfixes only and Y would be new features or any sort of changes. Depends on whoever would step up to do this and how much effort they want to put in.

**Comment by jtaala** [comment]
Yes, it is probably worth starting up releases again - especially since Gnome 44 drop is here (or coming up in Arch and other distros).

I use PaperWM on Gnome 43 as a daily driver and haven't had many issues (and certainly none that would stop my daily use of it).  We've also had many bugs fixed over the last few months (even while adding new features) - in other words, now may be a good time to do a release for Gnome 43.

**Comment by jtaala** [comment]
I'm happy to package up a release for 43 and do up some release notes etc.

**Comment by Lythenas** [comment]
I think if we want distro packages to be available, we should definitively start doing tags/releases again. But as @smichel17 said we might want to choose a different versioning scheme (because e.g. develop supports multiple gnome versions). Although I don't particularly care about that.

More importantly I think we need to decide when to do a new release.

Also for the release notes (at leas for newer versions) we can probably just use the github generated release notes that are generated from PRs (and maybe add more information/pictures for important features).

**Comment by jtaala** [comment]
Hey @gombosg, closing this now.

See [releases page](https://github.com/paperwm/PaperWM/releases) (which now has releases for Gnome 43 and Gnome 44.

Let us know if you need anything else implemented to ease this.
