### ISSUE TITLE
When a window moves to another monitor, paperWM seems to "lose control" of it

### ISSUE THREAD

**Issue by acetylen** [paperwm/PaperWM#465]
I have two monitors aligned like so: 
![image](https://user-images.githubusercontent.com/42578370/212643750-5da3ee20-6011-4d40-8427-eaa65eb4ccc6.png)

Big one (primary) is 4k, small one is FHD. They're both scaled at 100%.

Whenever I open a new window on the big display, the leftmost window sort of "pops out"; it moves left and appears on the small monitor. After this it behaves as though it is in a scratch space (although the "scratch" item in the window menu is not ticked); the window can be moved with the mouse and resized. However, if pulled back onto the big monitor, it will be put _behind_ any window in the scrollable list.

Putting the window in the scratch space and bringing it back lets it back into the list, but that usually means the new leftmost window pops out instead.

There seems to be no indication in the logs that this happens.

This is on EndeavourOS, with the `gnome-shell-extension-paperwm-git` AUR package at version r1740.f3b4860-1. Gnome-shell is on version 43.2.

**Comment by jtaala** [comment]
Hey @acetylen, if you're still using PaperWM, let me know if you're still seeing this on a recent version (e.g. current `develop`, `release`, or install via https://extensions.gnome.org/extension/6099/paperwm.

**Comment by jtaala** [comment]
Closing as no response.

**Comment by smichel17** [comment]
I have seen a bug that might be the same as this.

I have 3 monitors. A 4k monitor in landscape orientation in the middle, and two 1440p monitors in portrait on either side. The three monitors are vertically centered. Sometimes— **I cannot reliably reproduce** —when moving a window from the middle to the right monitor via keyboard shortcuts, the window exhibits similar behavior to what's described here: It pops out into the scratch layer… kind of.

- When unfocused, it drops behind other windows. When focused, it comes back into the foreground.
- PaperWM seems to believe the window is still on the middle monitor.
    - Using keyboard shortcuts (meta-R, meta-F) to toggle window sizes uses the widths of the center monitor.
    - Using keyboard shortcuts to move the window to the monitor left moves it all the way to the left monitor, where it behaves normally-ish.
        - It's no longer in the scratch layer.
        - It resizes and whatnot properly (based on the left monitor).
        - Moving it to the monitor right correctly moves it to the center monitor.
        - Moving it to the monitor right again puts it back in the bugged semi-scratch state.

Some other info:

- I tried restarting the gnome session (alt-f2 → r, running x11). This did not fix the issue.
- I tried using my gnome system settings to move the position of the right (bugged) monitor. Then moved it back. This _did_ fix the issue.

This is not the first time it happened (it's pretty rare), but was the first time I played around with it long enough to produce any interesting observations. Unfortunately, since I can't reliably reproduce, I have no logs.
