### ISSUE TITLE
Default Focus Mode should be configurable

### ISSUE THREAD

**Issue by MasonFlint44** [paperwm/PaperWM#503]
It seems that PaperWM uses its default focus mode every time I log in. I much prefer the "Center" focus mode rather than the default behavior - it feels really nice on an ultrawide monitor! I believe there should be a setting or a way to easily configure which focus mode PaperWM uses by default. If this is already the case, then maybe we could add some documentation for configuring such a setting.

To be clear, I'm not proposing that we change the behavior of the "Default" or "Center" focus modes, only that we allow configuration of which focus mode is used on init.

**Comment by jtaala** [comment]
I note that this was suggested in https://github.com/paperwm/PaperWM/pull/482#issuecomment-1454707794 for those that want this behaviour on by default.... I just forgot to add it (this submitted enhancement request reminded me of it).

**Comment by jtaala** [comment]
Hey @MasonFlint44, I've now added a setting (which can be set via dconf for example) to set the default focus mode (see #504).

Hopefully this will be merged in soon, otherwise you can use / try it out in the [PaperWM-redux](https://github.com/PaperWM-redux/PaperWM) which has this now implemented (which you'd need to checkout and run the `install.sh` and logout/login as per usual).

Cheers!
