### ISSUE TITLE
Smart preview: make preview always float optimally in view

### ISSUE THREAD

**Issue by letavocado** [paperwm/PaperWM#506]
**Is your feature request related to a problem? Please describe.**
Preview window overflows screen when hovering cursor close to corners

[Screencast from 2023-04-06 09-18-46.webm](https://user-images.githubusercontent.com/31704887/230264045-cdbef327-07a7-4057-b688-796dddb0480a.webm)

**Describe the solution you'd like**
Make a smart preview that will always float optimally in view

**Additional context**
Gnome 43.4 (Wayland)

**Comment by jtaala** [comment]
Hey @letavocado!

Any definitions of what "float optimally" means?  Like, in the (vertical) center?  What about size? - note that the size is based off `mini-map` tile size (which can be changed in PaperWM settings, e.g. `Mini-map scale`).

Similarly, can you define what a "smart" preview for this enhancement would look like (e.g. how it would behave, what triggers it etc)?

Cheers.

**Comment by letavocado** [comment]
Hey @jtaala! Thank you!

I made a [Wireframe in Figma](https://www.figma.com/file/NZuZQWDRaRrPFKB4lJLSdm/PaperWM-smart-mini-map?t=LV79OuqUqCDJHtf9-1) for a visual explanation.

Same feature exists in [Tippy.js](https://atomiks.github.io/tippyjs/). When the float visual block (e.g. tooltip, mini-map) does not go beyond the screen, but positioned in the viewport.

**Comment by jtaala** [comment]
Ah, okay, this makes sense!  Now I understand.  Yes, this can be implemented.

I've actually just been playing around with a preview concept I've been thinking of ("peek" previews) - but might be a step too far.  Happy to implement smart preview (and also animate them in/out).

Anyways, I'll push up a draft PR soon (of peek) - zap me some feedback on that to see if that has any potential.

**Comment by jtaala** [comment]
P.S. I love tippy.js.

**Comment by jtaala** [comment]
@letavocado, see #507.

Here's what "peek" previewing would look like:

https://user-images.githubusercontent.com/30424662/230534886-b9d04460-48b2-40a8-bb0b-c60261e1ede8.mp4

**Comment by letavocado** [comment]
OMG!!! It looks amazing. This is more than I could have expected. I definitely fell in love with it. 😍😍😍

P.S. I love PaperWM.

**Comment by jtaala** [comment]
@letavocado, I've also pushed up #511 which implements your smart previews (always keeps them in view as the issues mentioned).

Not sure which one I like yet (smart previews or peek previews).

Also see https://github.com/paperwm/PaperWM/pull/507#issuecomment-1500591097, those issues (particularly the focusIcon placement) is likely due to another extension being used by you (my guess anyway) - given your topbar in your video you put up, e.g. 
![image](https://user-images.githubusercontent.com/30424662/230694993-cbcbcf33-00fa-45c4-8f17-28fc3029fea1.png)

If you did want to keep using another extension, that might conflict with PaperWM focusIcon, then an option would be to [hide the focusIcon in PaperWM as outlined here](https://github.com/paperwm/PaperWM#hiding-the-focus-mode-icon).
