### ISSUE TITLE
Extension settings scaling issues in Gnome

### ISSUE THREAD

**Issue by Anduril97** [paperwm/PaperWM#599]
**Describe the bug**
Hello! I am using your extension on Manjaro gnome and unfortunately have an old laptop with a low resolution screen (720p). When I go into the settings of the paperWM extension The settings window is larger than my screen's resolution so I am unable to view the lower half of the settings window, and the General tab does not have a scroll bar and it cannot be resized short enough.

**To Reproduce**
1. Go to Extension in Gnome
2. Click on paper WM settings
3. General tab bottom half of window is cut off due to low screen resolution

**Expected behavior**

**Screenshots**

**System information:**

Distribution: Arch Linux Manjaro
GNOME Shell 44.3
Display 1366x768

**Additional context**

**Comment by jtaala** [comment]
Oh dear... yes, I can see the issue here.  Until we can fix this here's a workaround to at least allow seeing/changing settings:

1. open settings;
2. press `Alt+F7` and you can then move the window offscreen (e.g. push it up so you can see the other settings);

You should also be able to hold `Super` and click drag a window to move it (you can change this to another action key  via `Gnome Tweaks`, e.g. in screenshot below I have mine set to `alt`):

![image](https://github.com/paperwm/PaperWM/assets/30424662/f76add24-a369-4e1e-8a2a-ee2f6ddba20d)

**Comment by Anduril97** [comment]
@jtaala thank you for your tips they are REALLY good to know in my situation  especially; wow I had no idea!

**Comment by mahdi7d1** [comment]
I had the exact same issue and didn't even knew what extra settings are hiding down there (on the same 1366x768) and through your help managed to work around it. The settings hiding down there where specially important for me because the orange position bar was annoying so I turned it off but before I didn't even knew I can.

**Comment by jtaala** [comment]
Hey all, so I'll look at fixing this in the next day or two.

Interestingly, I fixed this in the [gnome-45](https://github.com/paperwm/PaperWM/tree/gnome-45) branch, but now need to port that fix to the gnome 42-44.

Cheers!

**Comment by Anduril97** [comment]
Thank you for fixing this @jtaala !
