### ISSUE TITLE
Configure behavior when scrolling on workspace name

### ISSUE THREAD

**Issue by josephcagle** [paperwm/PaperWM#604]
I tend to jump between workspaces a lot, and I tend to remember the workspaces' individual numbers better than the order in which I last used them.
I like the super+pgup/down functionality and animation that switches between workspaces in numerical sequence, and I don't find the "last used" order triggered by super+above_tab to be very useful for me.

Could a setting be added to allow using the sequential switcher, instead of the last-used switcher, when the user scrolls the mouse wheel while hovering over the workspace name in the top bar?

**Comment by jtaala** [comment]
Hey @DarthFloopy.  Sorry for the delay in replying - I've been working on Gnome 45 compatibility (which turned to be a much bigger job).

Anyways, yeah I could see the usefulness here.  It's not a big change to do it so will have a look at this.  If you wanted test this or give it a go yourself, you would change:

https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L427

to `Tiling.spaces._initWorkspaceSequence();`

And these lines:
https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L450
https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L453
https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L485
https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L538
https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L541
https://github.com/paperwm/PaperWM/blob/3986699cd814ffdd7a1aa65f30ffe4d31df83d52/topbar.js#L542

to use `spaces.selectSequenceSpace` instead.

Otherwise, can wait til we get time to look at this request.

Cheers!

**Comment by jtaala** [comment]
Closing this one as #833 fixes this (and implements this as standard behaviour).
