### ISSUE TITLE
warning on enable: No JS module 'examples' found in search path

### ISSUE THREAD

**Issue by KiaraGrouwstra** [paperwm/PaperWM#623]
**Describe the bug**
sometimes when enabling paperwm i am met with a harmless warning:
> Error occurred in user @init:
> No JS module 'examples' found in search path

**To Reproduce**
1. ???
2. enable paperwm
3. see warning

**Expected behavior**
no warning

**Screenshots**
![Screenshot from 2023-10-07 16-42-56](https://github.com/paperwm/PaperWM/assets/3059397/c9d58ab8-4c65-4fe1-ab62-8f1dca6f70ec)

**System information:**
(using nixos with nixpkgs:master, can't find the script but paperwm 17, gnome 44.4, other extensions: `emoji-copy`, `switch-x11-wayland`)

**Additional context**
n/a

**Comment by jtaala** [comment]
@KiaraGrouwstra, 

You have code in `~/.config/paperwm/user.js` that's outside of the control of PaperWM.

Either remove the `user.js` file or check `~/.config/paperwm/user.js` and remove things in it's `init` method that reference modules in `example/...`.

Note: in Gnome 45, `user.js` isn't working/supported due to changes implemented on the Gnome side (ESM modules): https://github.com/paperwm/PaperWM/issues/576#issuecomment-1721315729

**Comment by jtaala** [comment]
P.S. looks like you're using an EGO version of PaperWM?

Latest EGO version is 29 btw (17 is quite old now).

Also, EGO version doesn't include `examples` folder (examples were meant as examples, and could be copied into `user.js`, noting the issue above re Gnome 45).
