### ISSUE TITLE
Minimizing windows to Dash and then re-open them from the Dash doesn't get them tiled beneath the already opened windows.

### ISSUE THREAD

**Issue by kskruffnekk** [paperwm/PaperWM#661]
**Describe the bug**
Minimizing windows to Dash and then re-open them from the Dash doesn't get them tiled beneath the already opened windows, they are floating above the other tiled windows.

Is that intended?

**To Reproduce**
Minimize any App to Dash and then re-open them from Dash.

**Expected behavior**
The App gets tiled beneath the already opened Apps.

**Screenshots**
No screenshots needed.

Example:
Distribution: Arch Linux
GNOME Shell 45
Enabled extensions:
- paperwm
- dash-to-dock
- appindicatorsupport

**Comment by jtaala** [comment]
Hey @kskruffnekk.

Yes, this is by design.  Any window that's taken out of tiling (e.g. not managed by PaperWM tiling) - which minimising a window and restoring it will do, is added to the scratch layer (which is floating, and visible across PaperWM spaces, always on top etc.).

Users can re-add to the tiling layer via the `Attach/detach the active window into the scratch layer` keybind (default `Ctrl+Super+Escape`) or by right-clicking the windows titlebar (or using gnome's window options, e.g. `alt+space`) and unselecting the `Scratch` option (which will be ticked) e.g.

![image](https://github.com/paperwm/PaperWM/assets/30424662/4f1fb637-3096-41aa-b27b-1fc819173a1f)

**Comment by jtaala** [comment]
Please see this section for more info on the scratch layer: https://github.com/paperwm/PaperWM#scratch-layer

**Comment by kskruffnekk** [comment]
Thank you so much for clarification!
