### ISSUE TITLE
PaperWM hides the fedora branding logo

### ISSUE THREAD

**Issue by anonlegionoke** [paperwm/PaperWM#706]
**Describe the bug**
PaperWM hides the fedora branding logo even after selecting the default GNOME Shell background
**To Reproduce**
1. Install PaperWM on fedora workstation
2. It hides the fedora watermark on the background
3. Select Gnome default shell background in preferences
4. Still the background logo is not visible
5. Disable the PaperWM extension, logo appears again

**Expected behavior**
PaperWM doesnot affect the fedora branding logo and it remain visible
**Screenshots**

**System information:**
Please execute `./gather-system-info.sh` in you PaperWM clone and paste the output below.
Distribution : Fedora 39
GNOME Shell: 45
```
Example:
Distribution: Arch Linux
GNOME Shell 43.3
PaperWM branch/tag: develop
PaperWM commit: 223ff883bca9bf20dbf066eceda891cb6e8be931
Enabled extensions:
- paperwm@paperwm.github.com
- switcher@landau.fi
- dash-to-panel@jderose9.github.com
- appindicatorsupport@rgcjonas.gmail.com
```

**Additional context**

**Comment by jtaala** [comment]
This is interesting - I've never seen the fedora branding logo on my fedora instances.

I wonder what element they're using using here? (since it can't be part of the actual background/wallpaper).  For PaperWM to function (and actually hide windows that are tiled offscreen) it uses the copy of the background specifically designed to hide Clutter window clones (since mutter doesn't actually allow windows that far offscreen).

In any case, we'd need to replicate Fedora's custom element for this on all PaperWM backgrounds - which I'm not interested in doing (and can't see the value in - unless the branding / logo serves another purpose as well?).  

However, if you (or anyone) would like to give this a go, I'd accept a PR that implements this.

**Comment by jtaala** [comment]
Do we know of any other distros that add a watermark element?

**Comment by jtaala** [comment]
@anonlegionoke - can you post a screenshot of the background/watermark here?

**Comment by jtaala** [comment]
Did you enable the fedora watermark somehow? (or was it on by default in your install?).  

Let us know and we'd then be able to see how it's being implemented.

Wait, it's not this is it? https://www.youtube.com/watch?v=xNoE7x5SlHo

**Comment by anonlegionoke** [comment]
I haven't seen it on any other distros other than fedora. They are achieving this with an extension, but what is available on gnome extensions website now seems like a very old one(Link below).  

https://extensions.gnome.org/extension/889/background-logo/

But the one that fedora gnome ship with works flawlessly.

Screenshots below

![Screenshot from 2023-11-21 14-31-51](https://github.com/paperwm/PaperWM/assets/127176580/01ab9d20-d0df-4f01-8b1b-eab28ca113ea)


![Screenshot from 2023-11-21 14-31-42](https://github.com/paperwm/PaperWM/assets/127176580/9c434772-8abe-4c90-a29a-dc11ef3c4333)

**Comment by anonlegionoke** [comment]
> Did you enable the fedora watermark somehow? (or was it on by default in your install?).
> 
> Let us know and we'd then be able to see how it's being implemented.
> 
> Wait, it's not this is it? https://www.youtube.com/watch?v=xNoE7x5SlHo

It is indeed an extension, also it is a built-in extension on a fedora clean installation.

**Comment by jtaala** [comment]
Ah I see - yeah, I wouldn't work on this (too many other things to fix/work on).  Will leave this up though in case you or others want to implement this element for PaperWM (it would need custom replication since the backgrounds in PaperWM are not actually the Gnome backgrounds / wallpaper objects).

I implemented [support for dynamic wallpapers](https://github.com/paperwm/PaperWM/issues/637) recently - same type of issue, we needed to implement our own version at the element/actor level.

**Comment by Thesola10** [comment]
Seeing as this is not a GNOME built-in feature, but a custom Actor painted over the wallpaper layer, I'm not sure if it should be up to PaperWM to address this issue.

Unless there is an extension-agnostic way to detect and transpose any Actors trying to draw behind windows

**Comment by jtaala** [comment]
Closing as out-of-scope.  We would accept a PR for this, but it's not something that we'd work on.
