### ISSUE TITLE
Only a part of window is visible when entering Full Screen mode for videos.

### ISSUE THREAD

**Issue by anonlegionoke** [paperwm/PaperWM#750]
**Describe the bug**
Only a part of window is visible when entering Full Screen mode. 
Only top left corner of the video is visible at the bottom left corner of the screen. Rest is all black!

**To Reproduce**
1. Go to 'Any video watching website like Youtube, or Video sent on Telegram'
2. Click on 'Full screen  button'
3. See the bug

**Expected behavior**
Enter full screen normally filling the screen

**Screenshots**
![image](https://github.com/paperwm/PaperWM/assets/127176580/fe3fa7b3-edc6-4dee-bb21-40dbdc696517)
[Screencast from 2024-01-13 12-49-09.webm](https://github.com/paperwm/PaperWM/assets/127176580/940e5b33-a9e7-4360-8ce2-a5505eb07401)

**Comment by jtaala** [comment]
Hey @anonlegionoke,

This is actually an upstream gnome bug that fixed in Gnome 45.3 (and more specifically Mutter version 45.3).

You can check your current mutter version by running the following command from a terminal:

```
mutter --version
```

(the fixed version should output `mutter 45.3` - let us know what version you have though).

Hopefully your distro has these versions released soon.

See this issue discussing this https://github.com/paperwm/PaperWM/issues/638

**Comment by jtaala** [comment]
Closing as dupilcate of #638.

Update mutter to latest (version `45.3`).
