### ISSUE TITLE
Onboard cannot resize desktop

### ISSUE THREAD

**Issue by FrauH0lle** [paperwm/PaperWM#84]
The virtual keyboard [onboard](https://launchpad.net/onboard) has a nice feature which resizes GNOME's desktop if onboard is shown so the keyboard does not overlap any windows which might contain text which is edited.

If PaperWM is activated, this feature does not work and the following visual glitch can occur:
![bildschirmfoto von 2018-10-22 00-39-20](https://user-images.githubusercontent.com/10484857/47273362-800c5200-d593-11e8-8c63-65c284f54bf4.png)
Here, two terminals are open and when the lower one is selected, onboard moves to this top position (even though onboard's position  should be fixed at the bottom), It moves back to the bottom when the upper is selected.

**Edit:**
Onboard's movement can be inhibited by disabling its movement strategy as describe [here](https://bugs.launchpad.net/onboard/+bug/1584913).

**Comment by hedning** [comment]
I'm pretty sure onboard uses X11 stuff to scale windows, so that probably won't work correctly in Wayland (I'm unable to get input to work in Wayland too). Scaling window actors in gnome doesn't scale the input box, making mouse input buggy, so not sure how it would be done properly tbh.

In general to add some custom code to paperwm to do the scaling itself you'd have to something like this, though as mentioned above this would most likely make mouse input buggy:
```javascript
    Main.layoutManager.connect('keyboard-visible-changed', () => {
        if (Main.keyboard._keyboardRequested) {
            // scale down
        } else {
            // scale up
        }
    });
```

Now I'm not that motivated adding a custom fix for an external program, when gnome has a built in on screen keyboard which works in X11 and Wayland, though adding something to the `examples` folder would be fine.
