### ISSUE TITLE
Focus Follows Mouse

### ISSUE THREAD

**Issue by rawkode** [paperwm/PaperWM#863]
**Describe the bug**
Because the focus follows the cursor, whenever I need to get to another monitor; the windows on the current monitor all slide along.

My cursor is moving over them, but I don't want the focus to change unless I click on the window or use alt-tab.

**To Reproduce**
1. Open multiple windows / apps, not maximised.
2. Move mouse over another
3. Focus is changed

**Expected behavior**

Focus isn't changed

**Comment by Lythenas** [comment]
See also #389 for why we focus the other monitor when the mouse moves. We basically have to do it that way because we want one workspace per monitor and that is not how gnome normally works.

But I'm a bit confused about what you mean with

> the windows on the current monitor all slide along.

Focus should change when you move your mouse to another monitor, but no windows should move.

**Comment by rawkode** [comment]
The focus follows the cursor. So if I have 3 windows visible on a single monitor, this means that as I move my cursor the active window is the one under my cursor. With focus mode set to centre, the windows scroll around. This means when I move my cursor to the other monitor, the centre focus activates for each window is passea on the way. 

I want my focus to centre but only when I explicitly select a window; rather than hover.

**Comment by Lythenas** [comment]
Normally even with "focus mode center" the windows should not move, because PaperWM will focus the previously focused window of the monitor, which would already be in the center.

So it sounds like specifically a compatibility issue with "focus follows the cursor". Is the "focus follows the cursor" from another extension?

**Comment by rawkode** [comment]
I feel silly, I assumed PaperWM was doing this but it appears to be something else. 

Sorry

**Comment by Jak2k** [comment]
> I feel silly, I assumed PaperWM was doing this but it appears to be something else.

Have you changed the window focus setting in Tweaks?

**Comment by rawkode** [comment]
I didn't turn on window focus hover, it appears to be the default (with NixOS at-least).

Disabled and happy now!
