### ISSUE TITLE
dash to dock overlaying

### ISSUE THREAD

**Issue by unknownuser88** [paperwm/PaperWM#94]
Hi, thank you for great extension!!

when dock's auto-hide is disabled  (position: left) PaperWm puts windows under the dock

![image](https://user-images.githubusercontent.com/2427559/52619151-654f4780-2eba-11e9-9fc8-847d34d2fcc7.png)

**Comment by hedning** [comment]
Thanks :)

Did a quick fix on the [respect-workarea](https://github.com/paperwm/PaperWM/tree/respect-workarea) branch, did some light testing and it seems to work OK. The interaction with the clickable edge overlays (giving a preview of the almost hidden windows) is a bit wonky, so I'll look into a more robust fix for those.

**Comment by unknownuser88** [comment]
Wow thank you for quick response 
new changes looks great 
works for me !!

**Comment by unknownuser88** [comment]
but now my mouse didn't go to second monitor 
when I disable extension it works but it doesn't work with paperwm even after checkout master branch

**Comment by hedning** [comment]
Pushed an ad-hoc fix to respect-workarea.

I added a pressure barrier to the edges recently which makes it possible to activate the left/right window when in fullscreen, but the pointer gets stuck in the barrier making it difficult to switch monitors.

**Comment by unknownuser88** [comment]
I think it stop working after git pull 
now when I checkout 22b1a717f09a9e2b613e16d9dd5862f7e180eacc it works

**Comment by hedning** [comment]
Yeah, it was introduced in 2546b0d9e317c70f944382277e2b2434e38a528f

**Comment by hedning** [comment]
Build a proper fix for the stuck mouse pointer issue on the respect-workarea branch: b5a064099f44975f48c77965f80d66af337ff3c8

The left and right edges of the workarea still stops the mouse pointer, but after applying some pressure the pointer should be free to pass onto another monitor.

When the dash is on the left, the barrier will require pressure before targeting the dock:
![image](https://user-images.githubusercontent.com/71978/52661315-0ca39d00-2f02-11e9-8de5-1a7e745b8555.png)

 This isn't ideal and I'll most likely add a preference to disable the pressure barrier at least.

**Comment by hedning** [comment]
I think this should be mostly solved now.

Some notes:

- The edge overlays will now float properly below the dash, meaning the dash will always get input
- The pressure barrier is always positioned at the monitor edges, triggering it on the edge that contains the dash shouldn't do anything due to the above point
- The user will have to reselect/resize windows if the workarea changes, simply doing a layout on `workareas-changed` didn't work well as it changes every time a fullscreen window is activated
- The dash won't show on a workspace with at least one fullscreen window open, this isn't something we're able to fix as dash-to-dock only cares about there being a fullscreen window on the workspace

If you find any more edge-cases I'll try to get them fixed :)
