### ISSUE TITLE
In WinProp Config Window, specify workspace to open matching wm_class on

### ISSUE THREAD

**Issue by maxfridbe** [paperwm/PaperWM#949]
**Is your feature request related to a problem? Please describe.**
I constantly have to open things like firefox on Workspace 2 and chrome on Workspace 3 which I have to do manually switching and then running the command.

**Describe the solution you'd like**
In the Winprop screen, there can be another property that says "place on workspace" that can let me enter "*2" for workspaces containing 2 or "Workspace 2" full match.

**Describe alternatives you've considered**
Is there a scripting system in the config directory where I can program this? Claude says I can do this (is this true):
```javascript
//nano ~/.config/paperwm/user.js
var Meta = imports.gi.Meta;
var Main = imports.ui.main;

function onWindowCreated(display, window, noRecurse) {
  if (window.get_wm_class() == "Firefox") {
    let workspace = global.workspace_manager.get_workspace_by_index(1);
    if (workspace) {
      window.change_workspace(workspace);
    }
  }
}

global.display.connect('window-created', onWindowCreated);
```

**Additional context**

**Comment by Lythenas** [comment]
That code may have worked on Gnome 44 and older, but since Gnome 45 we can't support a `user.js` anymore. You could maybe make your own extension that does this (or use an existing one). I also thought we had this functionality in the past but I can't find any code for it :D

I think this would be a good feature to add. It is a common feature in tiling window managers. And it seem pretty simple to add.

I will try to take a stab at this, since I have some time.

**Comment by maxfridbe** [comment]
Thank you so much! For this project and for bothering, I am a dev and am constantly impressed when people do any work :-) 
On a side note, I HAD NEVER used a tiling window manager until I stumbled upon this extension, now cannot live without it!  Your extension made me a better person :100:
