### ISSUE TITLE
PaperWM Issues with Waydroid Multi-Window

### ISSUE THREAD

**Issue by ghost** [paperwm/PaperWM#970]
I’m using Zorin OS 17.2 with kernel 6.8, and I’m experiencing issues with PaperWM when trying to use Waydroid Multi-Window. 
Windows either fail to resize properly.

PaperWM enable:
![Captura de tela de 2024-11-19 05-35-11](https://github.com/user-attachments/assets/80e6e7cc-0dfb-4c3b-ab4a-031709e2cb6d)

PaperWM disabled, it works perfectly!
![Captura de tela de 2024-11-19 05-36-39](https://github.com/user-attachments/assets/0065756d-44d9-4183-a3c0-accb343bfda5)

I don't know how to use this:
![Captura de tela de 2024-11-19 05-33-12](https://github.com/user-attachments/assets/5723ff6b-98d5-434b-bafd-4336ee5a3392)

If anyone has faced a similar issue or knows how to configure Waydroid Multi-Window to work better with PaperWM, I’d greatly appreciate your advice!

**Comment by Lythenas** [comment]
The "preferred width" should only be the width as far as I remember. So "1080px" in your case. The window should automatically use the full height in PaperWM.

It also looks like the window is floating (not sure if it is), but you don't have it in the scratch layer, right? I don't remember if the width works properly there.

Since this is an emulator, it is also quite possible that the window will resize after it was initially created, so the initial preferred width will basically be ignored. I'm not familiar with Waydroid, so not sure if that applies here.

And just to clarify with "fail to resize properly" you mean only that the winprop does not work, right? Resizing it manually later works correctly?

**Comment by ghost** [comment]
I've tried everything, but the issue persists. The PaperWM window only exited fullscreen mode when it was adjusted to 1080x1920 px. The program can operate within this fixed space and 'float' in it, but the space itself does not move.

**Comment by ghost** [comment]
[Screencast from 2024-11-25 16-28-48.webm](https://github.com/user-attachments/assets/5756e029-fdae-4697-9d8c-06502c3f236a)
![Screenshot from 2024-11-25 16-40-33](https://github.com/user-attachments/assets/6a560d94-6b76-472c-9817-3fbd9b3eaeb4)

**Comment by ghost** [comment]
[Screencast from 2024-11-25 16-28-48.webm](https://github.com/user-attachments/assets/2a325744-3192-4fd7-9dd2-4ff3d95f90d7)

**Comment by ghost** [comment]
PaperWM also doesn't work on Waydroid, even with multi-window disabled.

**Comment by ghost** [comment]
> The "preferred width" should only be the width as far as I remember. So "1080px" in your case. The window should automatically use the full height in PaperWM.
> 
> It also looks like the window is floating (not sure if it is), but you don't have it in the scratch layer, right? I don't remember if the width works properly there.
> 
> Since this is an emulator, it is also quite possible that the window will resize after it was initially created, so the initial preferred width will basically be ignored. I'm not familiar with Waydroid, so not sure if that applies here.
> 
> And just to clarify with "fail to resize properly" you mean only that the winprop does not work, right? Resizing it manually later works correctly?

See it:
https://github.com/waydroid/waydroid/issues/1620

the bug really are in PaperWM

**Comment by Lythenas** [comment]
This is definitely a valid issue. At the moment I don't if or how we can fix it. When I get time I can try to take a closer look at Waydroid. In the past there were (kind of) similar issues with other applications, I think some of them we were also not able to fix. Some applications do "strange" things with the windows. Usually this is not noticeable, but PaperWM applies some hacks on top of gnome, so these things become an issue.

The best workaround I can think of is to just put the windows on the scratch layer (either manually or through a winprop). Although that means they are no longer tiled and are on top of all other windows, which is probably also annoying.

**Comment by ghost** [comment]
Thank you so much for your response. I've been using it in scratch mode for now because I can't stop using PaperWM—I absolutely LOVE it! I've never seen anything like it, and I can't live without it anymore. Don't worry or feel rushed; I just mentioned it to see if there was any solution. But I can still use Waydroid just fine, even with this bug. Thank you so much for this amazing extension!

**Comment by Thesola10** [comment]
Waydroid has a weird concept of windows -- the actual Wayland window occupies the entire screen, so it can hardly be tiled properly into PaperWM. I suppose this is because Android's SurfaceFlinger modifies rendering depending on where the window is on screen, and a lot of subtleties are better handled without fighting with the host window manager.

I don't think we're going to have a better solution than just sending Waydroid windows to scratch layer systematically, I added a winprop in #971 for reference.

**Comment by ghost** [comment]
Thank you, I'll read it.

**Comment by ghost** [comment]
It worked!! Thank you so much.

Unfortunately, it's not possible to use it with PaperWM's tiling setup, but it helped a lot!
